/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { NameMangling } from "../NameMangling";

export class NameManglingFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NameMangling {
    return new Contract(address, _abi, signerOrProvider) as NameMangling;
  }
}

const _abi = [
  {
    inputs: [],
    name: "works",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
