/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  NAME12mangling,
  NAME12manglingInterface,
} from "../../../v0.6.4/Name-Mangling/NAME12mangling";

const _abi = [
  {
    inputs: [],
    name: "provider",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "works",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class NAME12mangling__factory {
  static readonly abi = _abi;
  static createInterface(): NAME12manglingInterface {
    return new utils.Interface(_abi) as NAME12manglingInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NAME12mangling {
    return new Contract(address, _abi, signerOrProvider) as NAME12mangling;
  }
}
