import { OutputTransformer } from '.'

export const addPreambleOutputTransformer: OutputTransformer = (output) => {
  return addPreamble(output)
}

export function addPreamble(output: string): string {
  return [
    '/* Autogenerated file. Do not edit manually. */',
    '/* tslint:disable */',
    '/* eslint-disable */',
    output,
  ].join('\n')
}
