/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract } from "@ethersproject/contracts";
import { Interface } from "@ethersproject/abi";
import type { Signer } from "@ethersproject/abstract-signer";
import type { Provider } from "@ethersproject/providers";
import type {
  NestedLibrary,
  NestedLibraryInterface,
} from "../../../../v0.8.9/nested/b/NestedLibrary";

const _abi = [
  {
    inputs: [],
    name: "getValue",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

export class NestedLibrary__factory {
  static readonly abi = _abi;
  static createInterface(): NestedLibraryInterface {
    return new Interface(_abi) as NestedLibraryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider | undefined
  ): NestedLibrary {
    return new Contract(address, _abi, signerOrProvider) as NestedLibrary;
  }
}
