/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import { UnsignedTransaction } from "ethers/utils/transaction";
import { TypedEventDescription, TypedFunctionDescription } from ".";

interface Issue428ReproductionInterface extends Interface {
  functions: {};

  events: {
    Committed: TypedEventDescription<{
      encodeTopics([whitelist]: [null]): string[];
    }>;
  };
}

export class Issue428Reproduction extends Contract {
  connect(signerOrProvider: Signer | Provider | string): Issue428Reproduction;
  attach(addressOrName: string): Issue428Reproduction;
  deployed(): Promise<Issue428Reproduction>;

  on(event: EventFilter | string, listener: Listener): Issue428Reproduction;
  once(event: EventFilter | string, listener: Listener): Issue428Reproduction;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): Issue428Reproduction;
  removeAllListeners(eventName: EventFilter | string): Issue428Reproduction;
  removeListener(eventName: any, listener: Listener): Issue428Reproduction;

  interface: Issue428ReproductionInterface;

  functions: {};

  filters: {
    Committed(whitelist: null): EventFilter;
  };

  estimate: {};
}
