/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { EventFilter, Event } from "ethers";
import { Result } from "@ethersproject/abi";

export interface TypedEventFilter<T, G> extends EventFilter {}

export interface TypedEvent<T extends Result> extends Event {
  args: T;
}

export type TypedListener<T extends Array<any>, G> = (
  ...listenerArg: [...T, TypedEventFilter<T, G>]
) => void;
