/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface LibraryInterface extends ethers.utils.Interface {
  functions: {
    "other(uint8)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "other", values: [BigNumberish]): string;

  decodeFunctionResult(functionFragment: "other", data: BytesLike): Result;

  events: {};
}

export class Library extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: LibraryInterface;

  functions: {
    other(
      b: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: number;
    }>;

    "other(uint8)"(
      b: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: number;
    }>;
  };

  other(b: BigNumberish, overrides?: CallOverrides): Promise<number>;

  "other(uint8)"(b: BigNumberish, overrides?: CallOverrides): Promise<number>;

  callStatic: {
    other(b: BigNumberish, overrides?: CallOverrides): Promise<number>;

    "other(uint8)"(b: BigNumberish, overrides?: CallOverrides): Promise<number>;
  };

  filters: {};

  estimateGas: {
    other(b: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "other(uint8)"(
      b: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    other(
      b: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "other(uint8)"(
      b: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
