/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Dai } from "./Dai.js";
export * as factories from "./factories";
export { Dai__factory } from "./factories/Dai__factory.js";
