/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import { FactoryOptions } from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

module "hardhat/types/runtime" {
  function getContractFactory(
    name: "SafeMath",
    signerOrOptions?: ethers.Signer | FactoryOptions
  ): Promise<Contracts.SafeMath__factory>;
  function getContractFactory(
    name: "TestContract",
    signerOrOptions?: ethers.Signer | FactoryOptions
  ): Promise<Contracts.TestContract__factory>;
  function getContractFactory(
    name: "TestContract1",
    signerOrOptions?: ethers.Signer | FactoryOptions
  ): Promise<Contracts.TestContract1__factory>;
}
