/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
/*
  These types correspond to solidity contract code from source file:
  artifacts/contracts/TestContract1.sol/TestContract1.json
*/
export type { EdgeCases } from "./EdgeCases";
export type { SafeMath } from "./SafeMath";
export type { TestContract } from "./TestContract";
export type { TestContract1 } from "./TestContract1";

export { EdgeCases__factory } from "./factories/EdgeCases__factory";
export { SafeMath__factory } from "./factories/SafeMath__factory";
export { TestContract__factory } from "./factories/TestContract__factory";
export { TestContract1__factory } from "./factories/TestContract1__factory";
