/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { BigNumber } from "bignumber.js";

export interface PayableFactoryContract
  extends Truffle.Contract<PayableFactoryInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<PayableFactoryInstance>;
}

type AllEvents = never;

export interface PayableFactoryInstance extends Truffle.ContractInstance {
  newPayable: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<string>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };
}
