/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "../types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export declare namespace DataTypesPure {
  export type Struct1Struct =
    | [number | string | BN, number | string | BN]
    | { uint256_0: number | string | BN; uint256_1: number | string | BN };

  export type Struct1StructOutput = [string, string] & {
    uint256_0: string;
    uint256_1: string;
  };
}

export interface DataTypesPure extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): DataTypesPure;
  clone(): DataTypesPure;
  methods: {
    pure_address(): NonPayableTransactionObject<string>;

    pure_bool(): NonPayableTransactionObject<boolean>;

    pure_bytes(): NonPayableTransactionObject<string>;

    pure_bytes1(): NonPayableTransactionObject<string>;

    pure_enum(): NonPayableTransactionObject<string>;

    pure_int256(): NonPayableTransactionObject<string>;

    pure_int8(): NonPayableTransactionObject<string>;

    pure_named(): NonPayableTransactionObject<
      [string, string] & { uint256_1: string; uint256_2: string }
    >;

    pure_stat_array(): NonPayableTransactionObject<[string, string, string]>;

    pure_string(): NonPayableTransactionObject<string>;

    pure_struct(): NonPayableTransactionObject<DataTypesPure.Struct1StructOutput>;

    pure_tuple(): NonPayableTransactionObject<[string, string]>;

    pure_uint256(): NonPayableTransactionObject<string>;

    pure_uint8(): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
