/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
} from "ethers";
import type { ContractRunner } from "ethers/types/providers";

import type { Listener } from "ethers/src.ts/utils";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Events {
  export type EventDataStruct = { index: BigNumberish; name: string };

  export type EventDataStructOutput = [bigint, string] & {
    index: bigint;
    name: string;
  };
}

export interface EventsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "emit_anon1"
      | "emit_event1"
      | "emit_event2"
      | "emit_event3"
      | "emit_event3_overloaded"
      | "emit_event4"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AnonEvent1"
      | "Event1"
      | "Event2"
      | "Event3(bool,uint256)"
      | "Event3(uint256)"
      | "Event4"
      | "NoArgsEvent"
      | "UpdateFrequencySet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "emit_anon1",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emit_event1",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emit_event2",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emit_event3",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emit_event3_overloaded",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emit_event4",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "emit_anon1", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emit_event1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emit_event2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emit_event3",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emit_event3_overloaded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emit_event4",
    data: BytesLike
  ): Result;
}

export namespace AnonEvent1Event {
  export interface Object {
    value1: bigint;
  }
  export type Tuple = [value1: bigint];
  export type Event = TypedContractEvent<Tuple, Object>;
  export type Filter = TypedDeferredTopicFilter<Event>;
}

export namespace Event1Event {
  export interface Object {
    value1: bigint;
    value2: bigint;
  }
  export type Tuple = [value1: bigint, value2: bigint];
  export type Event = TypedContractEvent<Tuple, Object>;
  export type Filter = TypedDeferredTopicFilter<Event>;
}

export namespace Event2Event {
  export interface Object {
    arg0: bigint;
  }
  export type Tuple = [arg0: bigint];
  export type Event = TypedContractEvent<Tuple, Object>;
  export type Filter = TypedDeferredTopicFilter<Event>;
}

export namespace Event3_bool_uint256_Event {
  export interface Object {
    value1: boolean;
    value2: bigint;
  }
  export type Tuple = [value1: boolean, value2: bigint];
  export type Event = TypedContractEvent<Tuple, Object>;
  export type Filter = TypedDeferredTopicFilter<Event>;
}

export namespace Event3_uint256_Event {
  export interface Object {
    value1: bigint;
  }
  export type Tuple = [value1: bigint];
  export type Event = TypedContractEvent<Tuple, Object>;
  export type Filter = TypedDeferredTopicFilter<Event>;
}

export namespace Event4Event {
  export interface Object {
    data: Events.EventDataStructOutput;
  }
  export type Tuple = [data: Events.EventDataStructOutput];
  export type Event = TypedContractEvent<Tuple, Object>;
  export type Filter = TypedDeferredTopicFilter<Event>;
}

export namespace NoArgsEventEvent {
  export interface Object {}
  export type Tuple = [];
  export type Event = TypedContractEvent<Tuple, Object>;
  export type Filter = TypedDeferredTopicFilter<Event>;
}

export namespace UpdateFrequencySetEvent {
  export interface Object {
    arg0: string[];
    arg1: bigint[];
  }
  export type Tuple = [arg0: string[], arg1: bigint[]];
  export type Event = TypedContractEvent<Tuple, Object>;
  export type Filter = TypedDeferredTopicFilter<Event>;
}

export interface Events extends BaseContract {
  connect(runner: null | ContractRunner): BaseContract;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EventsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  emit_anon1: TypedContractMethod<[], [void], "nonpayable">;

  emit_event1: TypedContractMethod<[], [void], "nonpayable">;

  emit_event2: TypedContractMethod<[], [void], "nonpayable">;

  emit_event3: TypedContractMethod<[], [void], "nonpayable">;

  emit_event3_overloaded: TypedContractMethod<[], [void], "nonpayable">;

  emit_event4: TypedContractMethod<[], [void], "nonpayable">;

  getFunction(
    nameOrSignature: "emit_anon1"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emit_event1"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emit_event2"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emit_event3"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emit_event3_overloaded"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emit_event4"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AnonEvent1"
  ): TypedContractEvent<AnonEvent1Event.Tuple, AnonEvent1Event.Object>;
  getEvent(
    key: "Event1"
  ): TypedContractEvent<Event1Event.Tuple, Event1Event.Object>;
  getEvent(
    key: "Event2"
  ): TypedContractEvent<Event2Event.Tuple, Event2Event.Object>;
  getEvent(
    key: "Event3(bool,uint256)"
  ): TypedContractEvent<
    Event3_bool_uint256_Event.Tuple,
    Event3_bool_uint256_Event.Object
  >;
  getEvent(
    key: "Event3(uint256)"
  ): TypedContractEvent<
    Event3_uint256_Event.Tuple,
    Event3_uint256_Event.Object
  >;
  getEvent(
    key: "Event4"
  ): TypedContractEvent<Event4Event.Tuple, Event4Event.Object>;
  getEvent(
    key: "NoArgsEvent"
  ): TypedContractEvent<NoArgsEventEvent.Tuple, NoArgsEventEvent.Object>;
  getEvent(
    key: "UpdateFrequencySet"
  ): TypedContractEvent<
    UpdateFrequencySetEvent.Tuple,
    UpdateFrequencySetEvent.Object
  >;

  // TODO change this bucket to events once changed in ethers beta exports
  filters: {
    "AnonEvent1(uint256)": TypedContractEvent<
      AnonEvent1Event.Tuple,
      AnonEvent1Event.Object
    >;
    AnonEvent1: TypedContractEvent<
      AnonEvent1Event.Tuple,
      AnonEvent1Event.Object
    >;

    "Event1(uint256,uint256)": TypedContractEvent<
      Event1Event.Tuple,
      Event1Event.Object
    >;
    Event1: TypedContractEvent<Event1Event.Tuple, Event1Event.Object>;

    "Event2(uint256)": TypedContractEvent<
      Event2Event.Tuple,
      Event2Event.Object
    >;
    Event2: TypedContractEvent<Event2Event.Tuple, Event2Event.Object>;

    "Event3(bool,uint256)": TypedContractEvent<
      Event3_bool_uint256_Event.Tuple,
      Event3_bool_uint256_Event.Object
    >;
    "Event3(uint256)": TypedContractEvent<
      Event3_uint256_Event.Tuple,
      Event3_uint256_Event.Object
    >;

    "Event4(tuple)": TypedContractEvent<Event4Event.Tuple, Event4Event.Object>;
    Event4: TypedContractEvent<Event4Event.Tuple, Event4Event.Object>;

    "NoArgsEvent()": TypedContractEvent<
      NoArgsEventEvent.Tuple,
      NoArgsEventEvent.Object
    >;
    NoArgsEvent: TypedContractEvent<
      NoArgsEventEvent.Tuple,
      NoArgsEventEvent.Object
    >;

    "UpdateFrequencySet(address[],uint256[])": TypedContractEvent<
      UpdateFrequencySetEvent.Tuple,
      UpdateFrequencySetEvent.Object
    >;
    UpdateFrequencySet: TypedContractEvent<
      UpdateFrequencySetEvent.Tuple,
      UpdateFrequencySetEvent.Object
    >;
  };
}
