/**
 * Rename ugly names generated by solc to something human redable.
 * NOTE: we assume that there is only one contract per file
 */
const fs = require('fs')
const { join } = require('path')

const contractDir = join(__dirname, "../../contracts/compiled");

const files = fs.readdirSync(contractDir)

for (const file of files) {
  const renamed = file.replace(/^__contracts_([A-Za-z0-9-]+)_sol_([A-Za-z0-9-]*)\.([a-z]+)$/, '$1.$3')

  console.log(file, ' => ', renamed)
  fs.renameSync(join(contractDir, file), join(contractDir, renamed))
}
